# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: stop service
        run: systemctl --user stop covid19

      - name: install modules âœ…
        run: python3.8 -m pip install -r requirements.txt
      
      - name: remove exist file ðŸ—‘
        run: rm -rf ~/covid19
      
      - name: copy files ðŸšš
        run: cp -r * ~/covid19
      
      - name: write env ðŸŒ²
        run: |
          touch ~/covid19/.env
          echo DB_FULL=${{ secrets.DB_FULL }} >> .env
          echo TOKEN=${{ secrets.TOKEN }} >> .env
          echo LOG_CHANNEL=${{ secrets.LOG_CHANNEL }} >> .env
          echo GRAPH_CHANNEL=${{ secrets.GRAPH_CHANNEL }} >> .env
          echo THUNDER_ID=${{ secrets.THUNDER_ID }} >> .env

      - name: start service
        run: systemctl --user start covid19
